version: '3'
services:
  app:
    container_name: ${PROJECT_NAME}_app
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '${PORT}:${PORT}'
    expose:
      - ${PORT}



